# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "mrdavehill-demo-backend"
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "eu-west-1/infra/preprod/tgw/terraform.tfstate"
    region         = "eu-west-1"
  }
}
